# Generated by Django 6.1.1 on 2026-09-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('status', models.CharField(default='issued', max_length=8)),
                ('used_by', models.CharField(blank=True, max_length=64, null=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=32, unique=True)),
                ('format_label', models.CharField(max_length=40)),
                ('orientation', models.CharField(max_length=12)),
                ('width_cm', models.FloatField()),
                ('height_cm', models.FloatField()),
                ('colors', models.IntegerField()),
                ('price', models.FloatField()),
                ('discount_code', models.CharField(blank=True, max_length=32, null=True)),
                ('discount_amount', models.FloatField(default=0.0)),
                ('total', models.FloatField()),
                ('customer_name', models.CharField(max_length=120)),
                ('customer_email', models.EmailField(max_length=254)),
                ('supplier_ref', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
