# Generated by Django 6.1.1 on 2026-09-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0003_contactmessage_order_cost_order_lang'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.FloatField(default=19.0)),
                ('price_per_cm2', models.FloatField(default=0.006)),
                ('price_per_color', models.FloatField(default=0.4)),
                ('base_colors', models.IntegerField(default=12)),
                ('brushes_price', models.FloatField(default=3.0)),
                ('discount_rate', models.FloatField(default=0.15)),
                ('free_shipping', models.BooleanField(default=True)),
                ('cost_base', models.FloatField(default=6.0)),
                ('cost_per_cm2', models.FloatField(default=0.002)),
                ('cost_per_color', models.FloatField(default=0.15)),
                ('cost_shipping', models.FloatField(default=4.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Grille tarifaire',
                'verbose_name_plural': 'Grille tarifaire',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='address1',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='address2',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='brushes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='brushes_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='order',
            name='difficulty',
            field=models.CharField(default='moyen', max_length=12),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_code',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='order',
            name='postal_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
