# Generated by Django 6.1.1 on 2026-09-09 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0004_pricing_order_address1_order_address2_order_brushes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricing',
            name='base_colors',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='base_price',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='price_per_cm2',
        ),
        migrations.RemoveField(
            model_name='pricing',
            name='price_per_color',
        ),
        migrations.AddField(
            model_name='pricing',
            name='c_12',
            field=models.FloatField(default=0.0, verbose_name='12 couleurs (+)'),
        ),
        migrations.AddField(
            model_name='pricing',
            name='c_24',
            field=models.FloatField(default=8.0, verbose_name='24 couleurs (+)'),
        ),
        migrations.AddField(
            model_name='pricing',
            name='c_36',
            field=models.FloatField(default=16.0, verbose_name='36 couleurs (+)'),
        ),
        migrations.AddField(
            model_name='pricing',
            name='p_30x40',
            field=models.FloatField(default=24.9, verbose_name='30 x 40 cm'),
        ),
        migrations.AddField(
            model_name='pricing',
            name='p_40x50',
            field=models.FloatField(default=34.9, verbose_name='40 x 50 cm'),
        ),
        migrations.AddField(
            model_name='pricing',
            name='p_50x70',
            field=models.FloatField(default=49.9, verbose_name='50 x 70 cm'),
        ),
        migrations.AddField(
            model_name='pricing',
            name='p_60x80',
            field=models.FloatField(default=64.9, verbose_name='60 x 80 cm'),
        ),
        migrations.AddField(
            model_name='pricing',
            name='p_70x100',
            field=models.FloatField(default=84.9, verbose_name='70 x 100 cm'),
        ),
        migrations.AddField(
            model_name='pricing',
            name='p_80x120',
            field=models.FloatField(default=109.9, verbose_name='80 x 120 cm'),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='brushes_price',
            field=models.FloatField(default=3.0, verbose_name='Set de pinceaux'),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='discount_rate',
            field=models.FloatField(default=0.15, verbose_name='Taux de remise fidelite'),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='free_shipping',
            field=models.BooleanField(default=True, verbose_name='Livraison offerte'),
        ),
    ]
