# Generated by Django 6.1.1 on 2026-09-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0005_remove_pricing_base_colors_remove_pricing_base_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='kind',
            field=models.CharField(choices=[('loyalty', 'Fidelite (usage unique)'), ('promo', 'Promo (multi-usage)')], default='loyalty', max_length=8),
        ),
        migrations.AddField(
            model_name='discount',
            name='max_uses',
            field=models.IntegerField(default=1, verbose_name="Nombre d'utilisations (0 = illimite)"),
        ),
        migrations.AddField(
            model_name='discount',
            name='percent',
            field=models.IntegerField(default=15, verbose_name='Remise (%)'),
        ),
        migrations.AddField(
            model_name='discount',
            name='used_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pricing',
            name='av_30x40',
            field=models.BooleanField(default=True, verbose_name='30 x 40 dispo'),
        ),
        migrations.AddField(
            model_name='pricing',
            name='av_40x50',
            field=models.BooleanField(default=True, verbose_name='40 x 50 dispo'),
        ),
        migrations.AddField(
            model_name='pricing',
            name='av_50x70',
            field=models.BooleanField(default=True, verbose_name='50 x 70 dispo'),
        ),
        migrations.AddField(
            model_name='pricing',
            name='av_60x80',
            field=models.BooleanField(default=True, verbose_name='60 x 80 dispo'),
        ),
        migrations.AddField(
            model_name='pricing',
            name='av_70x100',
            field=models.BooleanField(default=True, verbose_name='70 x 100 dispo'),
        ),
        migrations.AddField(
            model_name='pricing',
            name='av_80x120',
            field=models.BooleanField(default=True, verbose_name='80 x 120 dispo'),
        ),
        migrations.AddField(
            model_name='pricing',
            name='av_brushes',
            field=models.BooleanField(default=True, verbose_name='Pinceaux dispo'),
        ),
        migrations.AddField(
            model_name='pricing',
            name='av_c12',
            field=models.BooleanField(default=True, verbose_name='12 couleurs dispo'),
        ),
        migrations.AddField(
            model_name='pricing',
            name='av_c24',
            field=models.BooleanField(default=True, verbose_name='24 couleurs dispo'),
        ),
        migrations.AddField(
            model_name='pricing',
            name='av_c36',
            field=models.BooleanField(default=True, verbose_name='36 couleurs dispo'),
        ),
    ]
