# Generated by Django 6.1.1 on 2026-09-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0006_discount_active_discount_kind_discount_max_uses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='delivery_days_max',
            field=models.IntegerField(default=9, verbose_name='Delai livraison max (jours)'),
        ),
        migrations.AddField(
            model_name='pricing',
            name='delivery_days_min',
            field=models.IntegerField(default=5, verbose_name='Delai livraison min (jours)'),
        ),
    ]
