# Generated by Django 6.1.1 on 2026-09-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0007_pricing_delivery_days_max_pricing_delivery_days_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='carrier',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Transporteur'),
        ),
        migrations.AddField(
            model_name='order',
            name='feedback_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='N° de suivi'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_url',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Lien de suivi'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente de paiement'), ('paid', 'Payee'), ('fulfilled', 'Envoyee au fournisseur'), ('shipped', 'Expediee'), ('delivered', 'Livree'), ('failed', 'Echouee')], default='pending', max_length=10),
        ),
    ]
