# Generated by Django 6.1.1 on 2026-09-11 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0008_order_carrier_order_feedback_sent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DigitalCanvas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('uid', models.CharField(max_length=40)),
                ('colors', models.IntegerField(default=24)),
                ('orientation', models.CharField(default='portrait', max_length=12)),
                ('width_cm', models.FloatField(default=40)),
                ('height_cm', models.FloatField(default=50)),
                ('source', models.CharField(default='digital', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('email', 'uid')},
            },
        ),
    ]
