# Generated by Django 6.1.1 on 2026-09-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0009_emailcode_digitalcanvas'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_30x40', models.FloatField(default=39.0, verbose_name='30x40')),
                ('d_40x50', models.FloatField(default=49.0, verbose_name='40x50')),
                ('d_50x70', models.FloatField(default=69.0, verbose_name='50x70')),
                ('d_60x80', models.FloatField(default=89.0, verbose_name='60x80')),
                ('d_70x100', models.FloatField(default=119.0, verbose_name='70x100')),
                ('d_80x120', models.FloatField(default=149.0, verbose_name='80x120')),
                ('av_30x40', models.BooleanField(default=True, verbose_name='30x40 dispo')),
                ('av_40x50', models.BooleanField(default=True, verbose_name='40x50 dispo')),
                ('av_50x70', models.BooleanField(default=True, verbose_name='50x70 dispo')),
                ('av_60x80', models.BooleanField(default=True, verbose_name='60x80 dispo')),
                ('av_70x100', models.BooleanField(default=True, verbose_name='70x100 dispo')),
                ('av_80x120', models.BooleanField(default=True, verbose_name='80x120 dispo')),
                ('m_toile', models.FloatField(default=0.0, verbose_name='Toile')),
                ('m_alu', models.FloatField(default=25.0, verbose_name='Aluminium')),
                ('m_acrylique', models.FloatField(default=40.0, verbose_name='Acrylique')),
                ('av_m_toile', models.BooleanField(default=True, verbose_name='Toile dispo')),
                ('av_m_alu', models.BooleanField(default=True, verbose_name='Aluminium dispo')),
                ('av_m_acrylique', models.BooleanField(default=True, verbose_name='Acrylique dispo')),
                ('f_noir', models.FloatField(default=25.0, verbose_name='Cadre noir')),
                ('f_bois', models.FloatField(default=30.0, verbose_name='Cadre bois')),
                ('f_blanc', models.FloatField(default=25.0, verbose_name='Cadre blanc')),
                ('av_f_noir', models.BooleanField(default=True, verbose_name='Cadre noir dispo')),
                ('av_f_bois', models.BooleanField(default=True, verbose_name='Cadre bois dispo')),
                ('av_f_blanc', models.BooleanField(default=True, verbose_name='Cadre blanc dispo')),
                ('av_glass', models.BooleanField(default=True, verbose_name='Sous verre dispo')),
                ('glass_price', models.FloatField(default=15.0, verbose_name='Supplement verre')),
                ('supplier_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail fournisseur impression')),
                ('supplier_url', models.CharField(blank=True, default='', max_length=300, verbose_name='API fournisseur impression')),
            ],
            options={
                'verbose_name': 'Tarifs Tableau fini (impression)',
                'verbose_name_plural': 'Tarifs Tableau fini (impression)',
            },
        ),
    ]
