# Generated by Django 6.1.1 on 2026-09-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0010_printpricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalcanvas',
            name='category',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='digitalcanvas',
            name='title',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
