# Generated by Django 6.1.1 on 2026-09-12 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0011_digitalcanvas_category_digitalcanvas_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printpricing',
            name='av_m_acrylique',
        ),
        migrations.RemoveField(
            model_name='printpricing',
            name='m_acrylique',
        ),
        migrations.AddField(
            model_name='printpricing',
            name='av_m_bois',
            field=models.BooleanField(default=True, verbose_name='Bois dispo'),
        ),
        migrations.AddField(
            model_name='printpricing',
            name='m_bois',
            field=models.FloatField(default=15.0, verbose_name='Bois'),
        ),
        migrations.AlterField(
            model_name='printpricing',
            name='d_30x40',
            field=models.FloatField(default=29.0, verbose_name='30x40'),
        ),
        migrations.AlterField(
            model_name='printpricing',
            name='d_40x50',
            field=models.FloatField(default=39.0, verbose_name='40x50'),
        ),
        migrations.AlterField(
            model_name='printpricing',
            name='d_50x70',
            field=models.FloatField(default=59.0, verbose_name='50x70'),
        ),
        migrations.AlterField(
            model_name='printpricing',
            name='d_60x80',
            field=models.FloatField(default=75.0, verbose_name='60x80'),
        ),
        migrations.AlterField(
            model_name='printpricing',
            name='d_70x100',
            field=models.FloatField(default=95.0, verbose_name='70x100'),
        ),
        migrations.AlterField(
            model_name='printpricing',
            name='d_80x120',
            field=models.FloatField(default=119.0, verbose_name='80x120'),
        ),
        migrations.AlterField(
            model_name='printpricing',
            name='f_blanc',
            field=models.FloatField(default=19.0, verbose_name='Cadre blanc'),
        ),
        migrations.AlterField(
            model_name='printpricing',
            name='f_bois',
            field=models.FloatField(default=24.0, verbose_name='Cadre bois'),
        ),
        migrations.AlterField(
            model_name='printpricing',
            name='f_noir',
            field=models.FloatField(default=19.0, verbose_name='Cadre noir'),
        ),
        migrations.AlterField(
            model_name='printpricing',
            name='glass_price',
            field=models.FloatField(default=12.0, verbose_name='Supplement verre'),
        ),
        migrations.AlterField(
            model_name='printpricing',
            name='m_alu',
            field=models.FloatField(default=20.0, verbose_name='Aluminium'),
        ),
    ]
