# Generated by Django 6.1.1 on 2026-09-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0012_remove_printpricing_av_m_acrylique_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='referral_physical_rate',
            field=models.FloatField(default=0.4, verbose_name='Parrainage via produit physique'),
        ),
        migrations.AddField(
            model_name='pricing',
            name='referral_rate',
            field=models.FloatField(default=0.2, verbose_name='Parrainage (partage digital)'),
        ),
    ]
