# Generated by Django 6.1.1 on 2026-09-14 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0013_pricing_referral_physical_rate_pricing_referral_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='contact/%Y/%m/')),
                ('original_name', models.CharField(blank=True, default='', max_length=200)),
                ('content_type', models.CharField(blank=True, default='', max_length=80)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='studio.contactmessage')),
            ],
        ),
    ]
