# Generated by Django 6.1.1 on 2026-09-14 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0014_contactattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='digitalcanvas',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
