# Generated by Django 6.1.1 on 2026-09-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0015_digitalcanvas_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitFormat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width_cm', models.PositiveIntegerField(default=40, verbose_name='Largeur (cm)')),
                ('height_cm', models.PositiveIntegerField(default=50, verbose_name='Hauteur (cm)')),
                ('price', models.DecimalField(decimal_places=2, default=34.9, max_digits=7, verbose_name='Prix (EUR)')),
                ('available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('sort', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'ordering': ['sort', 'width_cm', 'height_cm'],
                'unique_together': {('width_cm', 'height_cm')},
            },
        ),
    ]
