# Generated by Django 6.1.1 on 2026-09-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0017_seed_kitformats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nom')),
                ('active', models.BooleanField(default=True, verbose_name='Actif')),
                ('checkout', models.CharField(choices=[('kit', 'Kit a peindre'), ('print', 'Tableau fini'), ('all', 'Tous les checkouts')], default='kit', max_length=10, verbose_name='Checkout connecte')),
                ('integration', models.CharField(choices=[('email', 'E-mail'), ('api', 'API (webhook)')], default='email', max_length=10, verbose_name='Integration')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail commande')),
                ('api_url', models.URLField(blank=True, default='', verbose_name='URL API / webhook')),
                ('api_key', models.CharField(blank=True, default='', max_length=200, verbose_name='Cle API')),
                ('pricing', models.TextField(blank=True, default='', verbose_name='Grille tarifaire')),
                ('terms', models.TextField(blank=True, default='', verbose_name='Conditions de partenariat')),
                ('priority', models.PositiveIntegerField(default=0, verbose_name='Priorite (0 = premier)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['priority', 'name'],
            },
        ),
    ]
