# Generated by Django 6.1.1 on 2026-09-15 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0018_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='address',
            field=models.TextField(blank=True, default='', verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Banque'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='bic',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='BIC'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail contact'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact_name',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Contact'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='iban',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='IBAN'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='Notes internes'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Telephone'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='want_colors_json',
            field=models.BooleanField(default=False, verbose_name='Couleurs (JSON)'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='want_poster',
            field=models.BooleanField(default=False, verbose_name='Poster / palette'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='want_preview_svg',
            field=models.BooleanField(default=False, verbose_name='SVG coloriee'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='want_preview_tiff',
            field=models.BooleanField(default=True, verbose_name='TIFF coloriee'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='want_template_svg',
            field=models.BooleanField(default=False, verbose_name='SVG numerotee'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='want_template_tiff',
            field=models.BooleanField(default=True, verbose_name='TIFF numerotee'),
        ),
    ]
