# Generated by Django 6.1.1 on 2026-09-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0019_supplier_address_supplier_bank_name_supplier_bic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='want_poster',
        ),
        migrations.AddField(
            model_name='supplier',
            name='incoterms',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='Incoterms / livraison'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='lead_time_days',
            field=models.PositiveIntegerField(default=5, verbose_name='Delai production (jours)'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='production_notes',
            field=models.TextField(blank=True, default='', verbose_name='Process / consignes de production'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='want_order_json',
            field=models.BooleanField(default=True, verbose_name='Order JSON (consignee/order/couleurs)'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='want_poster_svg',
            field=models.BooleanField(default=False, verbose_name='Poster .svg'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='want_poster_tiff',
            field=models.BooleanField(default=False, verbose_name='Poster .tiff'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='want_colors_json',
            field=models.BooleanField(default=False, verbose_name='Couleurs brutes (JSON)'),
        ),
    ]
