# Generated by Django 6.1.1 on 2026-09-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0020_remove_supplier_want_poster_supplier_incoterms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='want_source',
            field=models.BooleanField(default=True, verbose_name='Photo source'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='want_poster_svg',
            field=models.BooleanField(default=True, verbose_name='Poster .svg'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='want_preview_svg',
            field=models.BooleanField(default=True, verbose_name='Apercu colorie .svg'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='want_preview_tiff',
            field=models.BooleanField(default=False, verbose_name='Apercu colorie .tiff'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='want_template_svg',
            field=models.BooleanField(default=True, verbose_name='Toile numerotee .svg'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='want_template_tiff',
            field=models.BooleanField(default=True, verbose_name='Toile numerotee .tiff'),
        ),
    ]
