# Generated by Django 6.1.1 on 2026-09-17 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0021_supplier_want_source_alter_supplier_want_poster_svg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='want_colors_json',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='want_poster_svg',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='want_poster_tiff',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='want_preview_tiff',
        ),
        migrations.AddField(
            model_name='supplier',
            name='want_poster',
            field=models.BooleanField(default=True, verbose_name='Poster (PNG)'),
        ),
    ]
