# Generated by Django 5.2.17 on 2026-09-24 11:13

import django.db.models.deletion
from django.db import migrations, models


def backfill(apps, schema_editor):
    Order = apps.get_model("studio", "Order")
    Order.objects.filter(status_changed_at__isnull=True).update(status_changed_at=models.F("created_at"))


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0022_remove_supplier_want_colors_json_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="notes",
            field=models.TextField(
                blank=True, default="", verbose_name="Notes internes"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="status_changed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Statut depuis"
            ),
        ),
        migrations.CreateModel(
            name="OrderEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("at", models.DateTimeField(auto_now_add=True)),
                ("kind", models.CharField(default="status", max_length=12)),
                ("status", models.CharField(blank=True, default="", max_length=10)),
                ("text", models.CharField(blank=True, default="", max_length=300)),
                ("user", models.CharField(blank=True, default="", max_length=150)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="studio.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evenement commande",
                "verbose_name_plural": "Historique commandes",
                "ordering": ["-at"],
            },
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
