# Generated by Django 5.2.17 on 2026-09-24 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0023_erp_order_events"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactmessage",
            options={
                "verbose_name": "Message contact",
                "verbose_name_plural": "Messages contact",
            },
        ),
        migrations.AlterModelOptions(
            name="digitalcanvas",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Toile / modele",
                "verbose_name_plural": "Toiles & modeles (catalogue)",
            },
        ),
        migrations.AlterModelOptions(
            name="discount",
            options={
                "verbose_name": "Code remise",
                "verbose_name_plural": "Codes remise",
            },
        ),
        migrations.AlterModelOptions(
            name="emailcode",
            options={
                "verbose_name": "Code de verification",
                "verbose_name_plural": "Codes de verification",
            },
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name": "Commande", "verbose_name_plural": "Commandes"},
        ),
        migrations.AlterModelOptions(
            name="supplier",
            options={
                "ordering": ["priority", "name"],
                "verbose_name": "Fournisseur",
                "verbose_name_plural": "Fournisseurs",
            },
        ),
    ]
