# Generated by Django 5.2.17 on 2026-09-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0024_erp_verbose_names"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketingAd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=24, unique=True)),
                (
                    "image_uid",
                    models.CharField(
                        db_index=True, max_length=40, verbose_name="Image"
                    ),
                ),
                (
                    "campaign",
                    models.CharField(
                        blank=True, default="", max_length=80, verbose_name="Campagne"
                    ),
                ),
                (
                    "variant",
                    models.CharField(
                        default="A", max_length=40, verbose_name="Variante"
                    ),
                ),
                ("kind", models.CharField(max_length=20, verbose_name="Gabarit")),
                ("label", models.CharField(blank=True, default="", max_length=80)),
                (
                    "fmt",
                    models.CharField(
                        choices=[("web", "Page web animee"), ("gif", "GIF")],
                        default="web",
                        max_length=4,
                    ),
                ),
                ("file_name", models.CharField(max_length=120)),
                (
                    "target_url",
                    models.CharField(
                        default="https://paintit.click/create/",
                        max_length=300,
                        verbose_name="Lien cible",
                    ),
                ),
                ("texts", models.JSONField(blank=True, default=dict)),
                ("views", models.PositiveIntegerField(default=0, verbose_name="Vues")),
                (
                    "clicks",
                    models.PositiveIntegerField(default=0, verbose_name="Clics"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Pub marketing",
                "verbose_name_plural": "Pubs marketing (A/B)",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="order",
            name="ad_ref",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=24,
                verbose_name="Pub d'origine (A/B)",
            ),
        ),
    ]
