# Generated by Django 5.2.17 on 2026-09-24 11:47

import django.db.models.deletion
from django.db import migrations, models


def backfill(apps, schema_editor):
    Ad = apps.get_model("studio", "MarketingAd")
    Ad.objects.update(unique_clicks=models.F("clicks"))   # jusqu'ici : 1 clic max par visiteur


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0025_marketing_ab"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketingad",
            name="last_click_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Dernier clic"
            ),
        ),
        migrations.AddField(
            model_name="marketingad",
            name="test_clicks",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Clics internes (staff)"
            ),
        ),
        migrations.AddField(
            model_name="marketingad",
            name="unique_clicks",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Clics (visiteurs uniques)"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="studio.supplier",
                verbose_name="Fournisseur",
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="last_sync_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Derniere transmission"
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="last_sync_error",
            field=models.CharField(
                blank=True, default="", max_length=300, verbose_name="Derniere erreur"
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="last_sync_ok",
            field=models.BooleanField(
                default=True, verbose_name="Derniere transmission OK"
            ),
        ),
        migrations.AlterField(
            model_name="marketingad",
            name="clicks",
            field=models.PositiveIntegerField(default=0, verbose_name="Clics (total)"),
        ),
        migrations.AlterField(
            model_name="marketingad",
            name="views",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Vues (visiteurs uniques)"
            ),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
