# Generated by Django 5.2.17 on 2026-09-24 12:13

from django.db import migrations


def fix_referrals(apps, schema_editor):
    """Codes de parrainage auto (<uid>-R) crees en promo illimitee -> usage unique.
    Les promos saisies a la main ne sont pas touchees."""
    Discount = apps.get_model("studio", "Discount")
    for d in Discount.objects.filter(kind="promo", max_uses=0, code__endswith="-R"):
        d.kind = "loyalty"
        d.max_uses = 1
        if d.used_count > 0:
            d.status = "used"
        d.save(update_fields=["kind", "max_uses", "status"])



class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0026_clicks_suppliers"),
    ]

    operations = [
        migrations.RunPython(fix_referrals, migrations.RunPython.noop),
    ]
