# Generated by Django 5.2.17 on 2026-09-24 12:36

from django.db import migrations, models


def fill_secrets(apps, schema_editor):
    import secrets
    Supplier = apps.get_model("studio", "Supplier")
    for sup in Supplier.objects.filter(webhook_secret=""):
        sup.webhook_secret = secrets.token_urlsafe(24)
        sup.save(update_fields=["webhook_secret"])


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0027_referral_single_use"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="auto_dispatch",
            field=models.BooleanField(
                default=True,
                help_text="Sinon la commande attend une validation manuelle (Centre d'actions).",
                verbose_name="Transmission automatique au paiement",
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="webhook_secret",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Signe les envois (X-PaintIt-Signature) et authentifie les retours du fournisseur.",
                max_length=64,
                verbose_name="Secret webhook",
            ),
        ),
        migrations.RunPython(fill_secrets, migrations.RunPython.noop),
    ]
