# Generated by Django 5.2.17 on 2026-09-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0028_supplier_automation"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="want_template_pdf",
            field=models.BooleanField(
                default=True, verbose_name="Toile numerotee PDF vectoriel"
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="want_order_json",
            field=models.BooleanField(
                default=True,
                verbose_name="Fiche commande JSON (livraison/format/couleurs, sans prix)",
            ),
        ),
    ]
