# Generated by Django 5.2.17 on 2026-09-24 13:21

import django.db.models.deletion
from django.db import migrations, models


def copy_answers(apps, schema_editor):
    """Les anciennes reponses (champ unique ContactMessage.answer) deviennent le 1er element du fil."""
    Msg = apps.get_model("studio", "ContactMessage")
    Reply = apps.get_model("studio", "MessageReply")
    for m in Msg.objects.exclude(answer=""):
        r = Reply.objects.create(message=m, body=m.answer, user="")
        if m.answered_at:
            Reply.objects.filter(pk=r.pk).update(at=m.answered_at)


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0029_supplier_pdf_json"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageReply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField()),
                ("attachments", models.JSONField(blank=True, default=list)),
                ("user", models.CharField(blank=True, default="", max_length=150)),
                ("sent", models.BooleanField(default=True)),
                ("at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="studio.contactmessage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reponse",
                "verbose_name_plural": "Reponses",
                "ordering": ["at"],
            },
        ),
        migrations.RunPython(copy_answers, migrations.RunPython.noop),
    ]
