# Generated by Django 5.2.17 on 2026-09-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0030_message_replies"),
    ]

    operations = [
        migrations.AddField(
            model_name="digitalcanvas",
            name="origin_uid",
            field=models.CharField(
                blank=True, default="", max_length=40, verbose_name="Toile d'origine"
            ),
        ),
    ]
