# Generated by Django 5.2.17 on 2026-09-24 13:34

from django.db import migrations, models


def fill_slugs(apps, schema_editor):
    """Modeles existants : assets du home nommes d'apres l'uid sans 'gal-' (convention des dossiers plats)."""
    D = apps.get_model("studio", "DigitalCanvas")
    for m in D.objects.filter(email="__library__", uid__startswith="gal-", showcase_slug=""):
        m.showcase_slug = m.uid[4:]
        m.save(update_fields=["showcase_slug"])


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0031_canvas_origin"),
    ]

    operations = [
        migrations.AddField(
            model_name="digitalcanvas",
            name="in_slider",
            field=models.BooleanField(
                default=True, verbose_name="Dans le slider de l'accueil"
            ),
        ),
        migrations.AddField(
            model_name="digitalcanvas",
            name="showcase_slug",
            field=models.CharField(
                blank=True, default="", max_length=80, verbose_name="Assets du slider"
            ),
        ),
        migrations.RunPython(fill_slugs, migrations.RunPython.noop),
    ]
