# Generated by Django 5.2.17 on 2026-09-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studio", "0032_home_slider"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "legal_name",
                    models.CharField(
                        default="", max_length=120, verbose_name="Raison sociale / nom"
                    ),
                ),
                (
                    "legal_form",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="ex. SAS, SARL, Entreprise individuelle (micro-entreprise)",
                        max_length=60,
                        verbose_name="Forme juridique",
                    ),
                ),
                (
                    "capital",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=40,
                        verbose_name="Capital social",
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True, default="", verbose_name="Adresse du siège"
                    ),
                ),
                (
                    "siret",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="SIRET"
                    ),
                ),
                (
                    "rcs",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="ex. RCS Paris 123 456 789",
                        max_length=80,
                        verbose_name="RCS / RM",
                    ),
                ),
                (
                    "vat_number",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=20,
                        verbose_name="N° TVA intracommunautaire",
                    ),
                ),
                (
                    "vat_rate",
                    models.FloatField(
                        default=0.0,
                        help_text="0 = franchise en base (« TVA non applicable, art. 293 B du CGI »)",
                        verbose_name="Taux de TVA (%)",
                    ),
                ),
                (
                    "director",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="Directeur de la publication",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        default="contact@paintit.click",
                        max_length=254,
                        verbose_name="E-mail de contact",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, default="", max_length=30, verbose_name="Téléphone"
                    ),
                ),
                (
                    "host",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="Hébergeur (nom, adresse, téléphone)",
                    ),
                ),
                (
                    "mediator",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="Médiateur de la consommation (nom, site)",
                    ),
                ),
                (
                    "invoice_prefix",
                    models.CharField(
                        default="F", max_length=10, verbose_name="Préfixe des factures"
                    ),
                ),
            ],
            options={
                "verbose_name": "Infos légales",
                "verbose_name_plural": "Infos légales",
            },
        ),
        migrations.AddField(
            model_name="order",
            name="invoice_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=24,
                verbose_name="N° de facture",
            ),
        ),
    ]
